### ISSUE TITLE
Inconsistent behavior between Parquet and JSON when chunks are missing

### ISSUE THREAD

**Issue by ashiklom** [fsspec/kerchunk#493] opened 2024-08-13 20:24 UTC
Taking the first file from here (https://noaa-goes17.s3.amazonaws.com/index.html#ABI-L1b-RadF/2022/001/00/) as an example:

The following code:

```python
import kerchunk.hdf
import json
                                                                                                                                                     
fname = "OR_ABI-L1b-RadF-M6C01_G17_s20220010000320_e20220010009386_c20220010009424.nc"
                                                                                                                                                     
h5chunks = kerchunk.hdf.SingleHdf5ToZarr(fname)
refs = h5chunks.translate()
                                                                                                                                                     
with open("test.json", "w") as f:
    f.write(json.dumps(refs, indent=2))
```

Produces the following JSON output (excerpt; slightly clipped):

```json
"..."
"Rad/.zarray": "{\"chunks\":[226,226],\"compressor\":null,\"dtype\":\"<i2\",\"fill_value\":1023, ..."
"Rad/.zattrs": "{\"_ARRAY_DIMENSIONS\":[\"y\",\"x\"],\"_Unsigned\":\"true\",\"add_offset\":-25.9"
"Rad/0.16": "base64:eAHt0DENAAAAAqDD/pk1iIwGNMWAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCAAQMGDBgwYMCA..."
"Rad/0.17": [
  "/css/geostationary/BackStage/GOES-17-ABI-L1B-FULLD/2022/001/00/OR_ABI-L1b-RadF-M6C01_G17_s202..."
  51538,
  1448
],
"Rad/0.18": [
  "/css/geostationary/BackStage/GOES-17-ABI-L1B-FULLD/2022/001/00/OR_ABI-L1b-RadF-M6C01_G17_s202..."
  52986,
  4155
],
"Rad/0.19": [
  "/css/geostationary/BackStage/GOES-17-ABI-L1B-FULLD/2022/001/00/OR_ABI-L1b-RadF-M6C01_G17_s202..."
  57141,
  5554
],
"Rad/0.20": [
  "/css/geostationary/BackStage/GOES-17-ABI-L1B-FULLD/2022/001/00/OR_ABI-L1b-RadF-M6C01_G17_s202..."
  22412,
  7527
],
"..."
```

Note that the radiance chunks begin at `0.16` --- there is no `Rad/0.{0--15}`. That's weird --- I'm assuming this is some HDF5 sparse data cleverness. But in any case, `xarray.open_dataset("test.json", engine="kerchunk")` and subsequent summarizing of the entire Rad array (`dat.Rad.mean().values`) works fine here.

However, if you spit this out as a Parquet dataset, then it produces a file with rows 0-15 containing `nan` paths and 0 values, and then the real data start at row 16. That's fine...except that reading that Parquet file fails with an error like this (full backtrace in details):

```
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/mapping.py", line 105, in getitems
    out = self.fs.cat(keys2, on_error=oe)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 836, in cat
    proto_dict = _protocol_groups(path, self.references)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 52, in _protocol_groups
    protocol = _prot_in_references(path, references)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 44, in _prot_in_references
    return split_protocol(ref[0])[0] if ref[0] else ref[0]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/core.py", line 544, in split_protocol
    if "://" in urlpath:
       ^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
```

I've traced this back to a `references.get("Rad/0.0")` call that returns a `nan` "url" that can't be parsed by subsequent code. Here's some relevant `pdb` traces:

```
> /gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/core.py(544)split_protocol()
-> if "://" in urlpath:
(Pdb) u
> /gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py(44)_prot_in_references()
-> return split_protocol(ref[0])[0] if ref[0] else ref[0]
(Pdb) ll
 41     def _prot_in_references(path, references):
 42         ref = references.get(path)
 43         if isinstance(ref, (list, tuple)):
 44  ->         return split_protocol(ref[0])[0] if ref[0] else ref[0]
(Pdb) p ref
[nan]
(Pdb) p path
'Rad/0.0.0'
(Pdb)

```

<details>

```
Traceback (most recent call last):
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/read.py", line 6, in <module>
    print(combined_ds.Rad.mean().values)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/_aggregations.py", line 1664, in mean
    return self.reduce(
           ^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/dataarray.py", line 3826, in reduce
    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/variable.py", line 1663, in reduce
    result = super().reduce(
             ^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/namedarray/core.py", line 912, in reduce
    data = func(self.data, **kwargs)
                ^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/variable.py", line 449, in data
    return self._data.get_duck_array()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 837, in get_duck_a
rray
    self._ensure_cached()
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 831, in _ensure_ca
ched
    self.array = as_indexable(self.array.get_duck_array())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 788, in get_duck_a
rray
    return self.array.get_duck_array()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 837, in get_duck_a
rray
    self._ensure_cached()
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 831, in _ensure_ca
ched
    self.array = as_indexable(self.array.get_duck_array())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 788, in get_duck_a
rray
    return self.array.get_duck_array()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 658, in get_duck_a
rray
    array = array.get_duck_array()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/coding/variables.py", line 81, in get_duck_array
    return self.func(self.array.get_duck_array())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 651, in get_duck_array
    array = self.array[self.key]
            ~~~~~~~~~~^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/backends/zarr.py", line 104, in __getitem__
    return indexing.explicit_indexing_adapter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/core/indexing.py", line 1015, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/xarray/backends/zarr.py", line 94, in _getitem
    return self._array[key]
           ~~~~~~~~~~~^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/zarr/core.py", line 798, in __getitem__
    result = self.get_orthogonal_selection(pure_selection, fields=fields)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/zarr/core.py", line 1080, in get_orthogonal_selection
    return self._get_selection(indexer=indexer, out=out, fields=fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/zarr/core.py", line 1343, in _get_selection
    self._chunk_getitems(
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/zarr/core.py", line 2179, in _chunk_getitems
    cdatas = self.chunk_store.getitems(ckeys, contexts=contexts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/zarr/storage.py", line 1426, in getitems
    results_transformed = self.map.getitems(list(keys_transformed), on_error="return")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/mapping.py", line 105, in getitems
    out = self.fs.cat(keys2, on_error=oe)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 836, in cat
    proto_dict = _protocol_groups(path, self.references)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 52, in _protocol_groups
    protocol = _prot_in_references(path, references)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/implementations/reference.py", line 44, in _prot_in_references
    return split_protocol(ref[0])[0] if ref[0] else ref[0]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb33/ashiklom/aist-eso/goes-virtualizarr/.pixi/envs/default/lib/python3.12/site-packages/fsspec/core.py", line 544, in split_protocol
    if "://" in urlpath:
       ^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
```

</details>

**Comment by martindurant** [comment] 2024-08-14 14:27
Thanks for the report, I'll look into it. What version of fsspec and kerchunk do you have?

**Comment by ashiklom** [comment] 2024-08-14 15:10
Thanks!

```
  name: kerchunk
  version: 0.2.6
  url: https://files.pythonhosted.org/packages/82/8c/117feba86c75d42b8434f8e65085165df4cd415c754bcde3df007f036293/kerchunk-0.2.6-py3-none-any.whl
  sha256: dc55fcea6560688ffc2390ff5882847fdf736982c1817553632a2bd7eb59de73

  name: fsspec
  version: 2024.6.1
  url: https://files.pythonhosted.org/packages/5e/44/73bea497ac69bafde2ee4269292fa3b41f1198f4bb7bbaaabde30ad29d4a/fsspec-2024.6.1-py3-none-any.whl
  sha256: 3cb443f8bcd2efb31295a5b9fdb02aee81d8452c80d28f97a6d0959e6cee101e
```

**Comment by martindurant** [comment] 2024-08-14 15:30
It may be worth trying with the most recent fsspec, if you get to it before I have a chance to look.

**Comment by ashiklom** [comment] 2024-08-14 17:19
Confirming that I hit the same error with the latest (GitHub) versions of `kerchunk` and `fsspec`:

```
  name: kerchunk
  version: 0.2.6.post22
  url: git+https://github.com/fsspec/kerchunk@5085fef3640cc0f5d4b0c067e61eff9fd9e90ecb

  name: fsspec
  version: 2024.6.1.post14+gee98ae3
  url: git+https://github.com/fsspec/filesystem_spec@ee98ae3cc43c68455d4632cb23dd57bb702e5684
```

For reference, here's the full script I'm using to test this out:

```python
from kerchunk import hdf, df
import fsspec.implementations.reference
from fsspec.implementations.reference import LazyReferenceMapper
import json
                                                                                                                                                                                            
fname = "/css/geostationary/BackStage/GOES-17-ABI-L1B-FULLD/2022/001/00/OR_ABI-L1b-RadF-M6C01_G17_s20220010000320_e20220010009386_c20220010009424.nc"
                                                                                                                                                                                            
h5chunks = hdf.SingleHdf5ToZarr(fname)
refs = h5chunks.translate()
                                                                                                                                                                                            
# Write to JSON
with open("test.json", "w") as f:
    f.write(json.dumps(refs, indent=2))
                                                                                                                                                                                            
# Write to parquet
fs = fsspec.filesystem("file")
out = LazyReferenceMapper.create(record_size=10_000, root="test.parq", fs=fs)
out.flush()
df.refs_to_dataframe(refs, "test.parq")
                                                                                                                                                                                            
# Test the read
                                                                                                                                                                                            
import xarray as xr
                                                                                                                                                                                            
tjson = xr.open_dataset("test.json", engine="kerchunk")
tparq = xr.open_dataset("test.parq", engine="kerchunk")
                                                                                                                                                                                            
tjson.Rad.mean().values  # This works fine
tparq.Rad.mean().values  # This fails
```

**Comment by martindurant** [comment] 2024-08-14 18:05
Please try with https://github.com/fsspec/filesystem_spec/pull/1663

**Comment by martindurant** [comment] 2024-08-15 14:31
OK, arrays with no references at all is another edge case that wasn't covered...

**Comment by martindurant** [comment] 2024-08-15 20:48
I wrote the following test as a minimal reproducer - but it doesn't show the problem at all. an you see a difference?
```
def test_parquet_no_data(m):
    lz = fsspec.implementations.reference.LazyReferenceMapper.create(
        "memory://out.parq", fs=m
    )

    g = zarr.open_group(lz, mode="w")
    arr = g.create_dataset(name="one", dtype="int32", shape=(10,), chunks=(5,), compression=None,
                           fill_value=1)
    lz.flush()

    assert (arr[:] == 1).all()
```

**Comment by ashiklom** [comment] 2024-08-22 20:49
Sorry for not getting back to this sooner.

I'm not really sure how to create a minimal reproducible example of this, but I have identified the problem: The variables in question are scalar variables with attributes but _no values_ (and therefore, _no offsets_). See details here for an example h5dump; note that the `STORAGE_LAYOUT -> OFFSET = HADDR_UNDEF`.

<details>

```
DATASET "processing_parm_version_container" {
   DATATYPE  H5T_STD_I32LE
   DATASPACE  SCALAR
   OBJECTID { 360287970189639730 }
   STORAGE_LAYOUT {
      CONTIGUOUS
      SIZE 0
      OFFSET HADDR_UNDEF
   }
   FILTERS {
      NONE
   }
   FILLVALUE {
      FILL_TIME H5D_FILL_TIME_IFSET
      VALUE  -2147483647
   }
   ALLOCATION_TIME {
      H5D_ALLOC_TIME_LATE
   }
   DATA {
   (0): -2147483647
   }
   ATTRIBUTE "L1b_processing_parm_version" {
      DATATYPE  H5T_STRING {
         STRSIZE 26;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      OBJECTID { 504403158265495552 }
      DATA {
      (0): "OR-PARM-RAD_G17_v01r00.zip"
      }
   }
   ATTRIBUTE "long_name" {
      DATATYPE  H5T_STRING {
         STRSIZE 44;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      OBJECTID { 504403158265495553 }
      DATA {
      (0): "container for processing parameter filenames"
      }
   }
}
```

</details>

I.e., The problem isn't so much that `hf[bad_variable].chunks is None` but rather that `hf[bad_variable].id.get_offset() is None`.

The relevant kerchunk code is here:

https://github.com/fsspec/kerchunk/blob/main/kerchunk/hdf.py#L613-L617

This returns an empty dict, because the `get_offset()` for this variable is `None`.

But, there are still `.zarray` and `.zattrs` values to be referenced because this is an empty variable with attributes. So, the result is a `refs` list that contains `.zarray` and `.zattrs` keys but no offsets (and therefore no chunks, no `refs.0.parq` file, and therefore the "file not found" error reported above when the parquet engine tries to look for this).

```
In [17]: refs["refs"]["processing_parm_version_container/.zarray"]
Out[17]: '{"chunks":[],"compressor":null,"dtype":"<i4","fill_value":-2147483647,"filters":null,"order":"C","shape":[],"zarr_format":2}'

In [18]: refs["refs"]["processing_parm_version_container/.zattrs"]
Out[18]: '{"L1b_processing_parm_version":"OR-PARM-RAD_G17_v01r00.zip","_ARRAY_DIMENSIONS":[],"long_name":"container for processing parameter filenames"}'
```

Digging deeper, it looks like the fsspec JSON reader "succeeds" here because it just loops over all the references in the JSON, without worrying about the need for every `.zattrs` and `.zarray` to have a corresponding `varname/0.0` chunk. (But presumably, this may fail downstream somewhere, when you try to request values for this array...).

https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/reference.py#L959-L980

However, the parquet loader fails here because it explicitly expects a references file to exist:

https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/reference.py#L159-L160

Specifically, it seems that, if the length of the object is zero, the implementation _automatically assumes the scalar is stored in a chunk called 0_. **This assumption is incorrect for the (unusual) case where the array is completely empty and has no offsets**.

https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/reference.py#L311-L316

**Comment by martindurant** [comment] 2024-08-30 01:09
OK, I think I understand. I'm short of time this week and next, but please ping me again, and I will sort it out.

**Comment by ashiklom** [comment] 2024-09-26 17:25
Hi! Just checking in to see if you've been able to make any progress on this. Let me know if there are any prototype implementations, PRs, etc. that you'd like me to test out.

Also, note that https://github.com/fsspec/filesystem_spec/pull/1663 _did_ actually solve the first part of this problem, which is arguably a bigger issue because I can't hack around that, whereas the empty variables issue can be hacked around by just removing the offending variables from the `.zmetadata` file.

**Comment by martindurant** [comment] 2024-10-01 14:14
Sorry, I've not been working on this. I'll try to find some time.

So there were two problems:
- attempt to access references marked as NULL (missing), fixed by the linked commit
- variables with no references at all, because they have only NULLs _or_ they have dimensions of `()`

**Comment by ashiklom** [comment] 2024-10-01 16:15
No worries! To clarify, the two issues are:

1. Variable arrays where only _certain_ chunks (but not all chunks) are missing. Example: GOES data linked above, where the `Rad` array starts at chunk `Rad/0.16` (but `Rad/0.0` through `Rad/0.15` are missing). I think this was resolved by the linked commit.
2. Variables that are only used as containers for attributes and have no data stored at all (i.e., dimensionality is `()`).

**Comment by martindurant** [comment] 2024-10-01 16:24
agreed

**Comment by martindurant** [comment] 2024-10-23 15:04
I am looking back at this, and it appears to me that the 2. case was also already solved (test function below). In this case, the data is a scalar value, and if there is no refs parquet file, then an access to the data looks like the fill value.

```
def test_parquet_no_references(m):
    lz = fsspec.implementations.reference.LazyReferenceMapper.create(
        "memory://out.parq", fs=m
    )

    g = zarr.open_group(lz, mode="w")
    arr = g.create_dataset(
        name="one",
        dtype="int32",
        shape=(),
        chunks=(),
        compression=None,
        fill_value=1,
    )
    lz.flush()

    assert arr[...].tolist() == 1  #  scalar, equal to fill value
```

Notice that `...` is the only way, I think, to get data from a scalar.

**Comment by keewis** [comment] 2024-10-23 17:15
> Notice that `...` is the only way, I think, to get data from a scalar.

you can use `arr.item()` if you know that you have a scalar, otherwise `.tolist` is also defined on scalars (`[...]` will transform the scalar into a 0d array, and `[()]` will transform a 0d array into a scalar).

**Closed** 2024-10-23 18:50 UTC
