### ISSUE TITLE
KeyError when using Parquet-converted JSON reference for NetCDF4 access over HTTP

### ISSUE THREAD

**Issue by sreesanjeevkg** [fsspec/kerchunk#474] opened 2024-07-05 14:21 UTC
Hello,

I’m currently working on a POC where I’m using Kerchunk to access NetCDF4 files over HTTP. I’ve encountered an issue:

When using the JSON reference file created by Kerchunk, everything works fine.
However, when I convert this JSON reference to Parquet format and try to use it, I’m encountering a KeyError.

Any idea on why this might be happening and how to resolve it?

![image](https://github.com/fsspec/kerchunk/assets/32449066/15712173-e306-4364-a5bf-8730c2e2058f)

![image](https://github.com/fsspec/kerchunk/assets/32449066/3a286501-93f4-4757-9a78-258c5ea8c145)

**Comment by martindurant** [comment] 2024-07-05 14:34
Is this public data you can share, and do you have a complete workflow I can follow.

**Comment by sreesanjeevkg** [comment] 2024-07-05 16:10
Sorry, this is not a public dataset I can share, I will share the workflow. The "urls" variable just contains the http paths for the .nc files.

Also, I am just reading the group "solar_zenith" but the KeyError seems to happen in a different group "Cloud_water_path_37_liquid".

<img width="818" alt="Screenshot 2024-07-05 at 11 04 52 AM" src="https://github.com/fsspec/kerchunk/assets/32449066/42ad2df4-dee9-4b34-8e56-a750cd86c66f">

**Comment by martindurant** [comment] 2024-07-05 16:47
It is, of course, harder to debug in that case :)

Since a number of things can get cached along the way, I recommend you try restarting your kernel after saving the initial JSONs, and after creating the merged JSON, and again after writing out the parquet - checking at each stage that the output looks reasonable. You should check the contents of combined.parq, the matadate file and subdirectories.

**Comment by sreesanjeevkg** [comment] 2024-07-05 17:05
Hey Martin, the files are publicly available for downloading

https://ladsweb.modaps.eosdis.nasa.gov/search/order/4/CLDPROP_D3_VIIRS_SNPP--5111/2024-06-21..2024-07-05/DB/World

You can change the dates as required; I had all files downloaded from start of Jan 2023 to May 2025

**Comment by martindurant** [comment] 2024-07-05 18:59
What is `fnmeta.identity` ?

**Comment by martindurant** [comment] 2024-07-05 20:00
OK, so the problem is, that the dataset is not wholly netCDF: there are deeper nested variables like Cloud_Water_Path_1621_PCL_Liquid/Histogram_Counts . This *should not* be a problem, but the conversion apparently lost some nested '.zgroup' keys like "Cloud_Water_Path_1621_PCL_Liquid/.zgroup"

**Comment by sreesanjeevkg** [comment] 2024-07-05 23:27
So, what do you propose? Is there any way I can use .parquets or should I continue with the combined JSON for now?

**Comment by martindurant** [comment] 2024-07-06 02:17
It's something we need to fix. You could work around it by opening the references as a filesystem with fsspec and writing the .zgroup files where needed with value b'{"zarr_format":2}'. You can also find these same from the json/dict version of the refs.

Since you had no trouble making/using the JSON version, do you need parquet references here? Perhaps you anticipate applying the workflow to a much bigger dataset in the future?

**Comment by sreesanjeevkg** [comment] 2024-07-06 15:52
Yeah, we anticipate reading around more than 15+ years of files, for now reading 1.5 years' worth makes the JSON to be around say 150MB, so when reading more than 15+ years' worth of files it will come around easy to be 1GB at least, will the metadata reading from the JSON be slow then?

**Comment by martindurant** [comment] 2024-07-06 18:12
Yes, I would say that loading 1GB of references will be noticeable in resource usage and time - especially if you are using distributed across a number of modest nodes (each process needs a copy of the decoded JSON).

( cc @TomNicholas , since you were asking about how big reference sets can get)

**Comment by sreesanjeevkg** [comment] 2024-07-06 18:48
Thank you so much, Martin. Can you please keep me posted on the issue. Also, should I close this issue now ?

**Comment by martindurant** [comment] 2024-07-08 14:50
We can close this when I fix the issue :)

**Closed** 2024-07-08 18:29 UTC
